CREATE TABLE ALUMNO (
   ID_ALUMNO NUMERIC(10,0) NOT NULL PRIMARY KEY,
   APELLIDO_PATERNO varchar2(60) NOT NULL,
   APELLIDO_MATERNO varchar2(60) NOT NULL,
   NOMBRE varchar2(60) NOT NULL,
   ID_TIPO_DOCUMENTO NUMERIC(2,0) NOT NULL,
   NRO_DOCUMENTO varchar2(20) NOT NULL,
   CORREO varchar2(20) NOT NULL,
   TELEFONO varchar2(20) NOT NULL,
   FECHA_REGISTRO DATE NOT NULL ,   
   ESTADO char(1) DEFAULT '1'
);